name: check_dataset
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]


jobs:
  ancientMetagenomeDirCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/SPAAM-workshop/AncientMetagenomeDirCheck.git
      - name: test ancient microbiome 
        run: ancientMetagenomeDirCheck ancient-microbiome/standards.tsv ancient-microbiome/ancient-microbiome.tsv
            